name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - run: ls
      - run: python3 main.py
      - run: pip install numpy
      - run: pip install pytest
      - run: pytest